### ISSUE TITLE
Built workers zip file from travis

### ISSUE THREAD

**Issue by matthewhanson** [AmericanRedCross/osm-stats-workers#14]
The deployment script creates the AWS resources needed, one of these being a lambda function running the workers code.  

The code is uploaded via a zip file, but needs to have all of the node modules installed for Node version 0.10.36, as this is the version of the nodejs runtime on lambda.    It would be easiest if a specific branch of the workers code could be retrieved from Travis, since it is built anyway during CI.

cc: @kamicut

**Comment by matthewhanson** [comment]
@smit1678 It looks like the zip file only contains the top level.   You'll need to specify the -r switch to zip to have it recurse into directories.

**Comment by smit1678** [comment]
@matthewhanson Good catch https://github.com/AmericanRedCross/osm-stats-workers/commit/0131796c31494b11ae7516a4174292eb1fa3c70e. 

We've implemented the first version of this that uses Travis to build, zip, and then commit the zip file to the gh-pages branch. 

Future ways to do this instead of using the gh-pages branch could be to look into building with Travis, committing built files to a `release` branch, and then using Travis to tag as a release and create a zip file of that release.

**Comment by matthewhanson** [comment]
This works as intended, closing.
