### ISSUE TITLE
Error processing changeset 37236535

### ISSUE THREAD

**Issue by kamicut** [AmericanRedCross/osm-stats-workers#16]
Something in changeset 37236535 is breaking the workers. 

cc @matthewhanson

**Comment by matthewhanson** [comment]
Catching the error in the geo buff calculation is not what to do in this case.    

For this particular changeset the problem is that these were all amenities that have been modified, but they do not contain a 'nodes' subelement.  In these cases only the tags have been modified. 

I'm not sure, would any 'modify' node changeset not contain a nodes dictionary?   Or only if the node location has not been changed?

What should we do in these cases?   I think we should count it as a building mod, but we can't do the geometry calculation.

**Comment by matthewhanson** [comment]
Fixed, and geometry calculation changed from buffer to convex hull.
