### ISSUE TITLE
No INSERTS occuring with `node bin/osm-changes.js`

### ISSUE THREAD

**Issue by rgwozdz** [AmericanRedCross/osm-stats-workers#43]
I execute `node bin/osm-changes.js` successfully (no errors).  But no data is getting inserted into the database - it remains empty after many hours. Are there additional options or settings that need to be configured?

**Comment by rgwozdz** [comment]
Closing until I can come up with more clues.

**Comment by rgwozdz** [comment]
Ok, I have a little more to go on.  Once i commented out the `initialSequence` options, the streams started flowing into the database.  Curious if I am circumventing something important by commenting out that option; ?

**Comment by mojodna** [comment]
(Sorry, I was on vacation, back now.)

It intentionally defaults to sequences that haven't occurred yet. By commenting it out, you're telling it to start with the currently-available replication event. By providing a sequence in the past, you can backfill data (I wouldn't recommend more than a week since it takes a while to catch up).
